
{% set name = "xorg-libXrandr" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: 72b922c2e765434e9e9f0960148070bd4504b288263e2868a4ccce1b7cf2767a

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
  host:
    - pthread-stubs ==0.3
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-libxrender {{ xorg_libxrender }}
    - xorg-libxext {{ xorg_libxext }}
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-util-macros ==1.20.2
  run:
    - {{ pin_compatible('xorg-libx11') }}

test:
  commands:
    - test -f $PREFIX/lib/libXrandr.dylib  # [osx]
    - test -f $PREFIX/lib/libXrandr.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxrandr
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxrandr
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org Xrandr library
  description: |
    The X.org Xrandr library.
extra:
  recipe-maintainers:
    - Xarthisius
    - pkgw
    - scopatz
