travis:
  secure:
    BINSTAR_TOKEN: bYmfYiWK7K27rXQHvCYSYEGMmgoUbi6dQzjOKpLzhcYeUdqqCDVrOQFAiyfSIgBUzKTC3TQZLeUfAbFhRi1MJvuUgKMKKwOIudyZZmqVYzaMKoupcVI7Mmvo5WnGai4lOBrbe+FLJFjmWNx7QWmJRXc8NYf79udlzk6Ch1me6i70A2RNR421kwfm08Y2SSRhiTMUerYNAvthLOKYUAZ9ibEn7BjrLIjE8E9QDFn9OA8KmyxWcxSgiTgA6hwz5MHb8IkPkPl0CMYG/CyxViqhO1pfr68zz2q64+JOUSiMMuYFRbaQc74Xbc4z2DGP46zll1fV+5KUZrfqJCy5R+7fpGFRZXldQ8HEu6DymFDRDpKdU2TNcO1TIooFCQUvIm+WH3PLbhXLqgvLmYzhHebUwOolX0jgHd1N6XaNeJJ1+I/iOKcTHymUqp6+ZaRyBobIEMSYf1WMlbwISHk1c4OpBJFblF/a2B+nNcJPBkX3+T8CogFFORHeKuAu34AFLHocEtYIF7SV5eG+rDlN+pZ+nVVbZ5rMSSK8USEJ2710Tyzm+lQcs4LMaBQHrFjFmnPyyU6JhmWx+hf3P008iSc5l/zOKdnv/anPyt5nA71cSJ4Ff0vZRtbvZopticauIxy+JERuFyj9IXnz4oy95zS8pdV+jjAiddWiIGInannZGNk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
