appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: oFwhV9o/Y7WP5wSKo9ePkmGWVq4lk7YbFajWyrBs4hI66RKfDSiyPqoY7LjwZpjr0ai1IWI56ueHUqbtWfWMen/SBkG3zSS5az5w5S5cZ7ppZS6DBRJu7RZCNM5JwViJqdEs9VxQOy4Bbso/S1zQ0byN/75IdiZc2b7Bq3svws6Zxw/3q3FvIhCbYmz4doNl426PMewfxrKQq6ukUTimw3wHB8N/nfCfNF0mJ+3HTPjmFLoBHGWBopDPkFnDuFoluTYk//eosxIlLU6865Wx7mCvAvOwSVi3VCvRzU8lkaJVU8B4P2VKNeVl2Tga7QR0S54ZFtt3nNjQjKr9gxBcIF5LVtnD+28jO8f5Wdl9dH1I1Q3hjfFlCELJeseV+N+B1yPTqWYTpV9iUbf8b+m7E8C2SaJHNg/SRMGXpMF4d07vSFkTgkxaXMhVTtggSiyuuEnZtFqKBwR2ZJXAVFSW02omNlwmW3HyW1EJ9BH1OE72wro8gjrRIjtVYP6lIUtdfznkJ7hStmsZVIJguMZgZ4nbtQFHoSwm3zXo/EpQo1d5gEM6Ggxehqzz62QOzeAiAyrtASj/kjrOSgCe0smgJyQVEz99nf2cqke6DtehegkV4cQIbiJdF34rvg1qhQc//idjEdxjQVQzjsjCFWgidiROpp/88esE2D3mGPYVneQ=}
